# Introduction to Python

- Simple calculator
- Data types
- Lists
- Functions
- Packages and methods


In [1]:
# Python as a calculator
# Note: when we use '#' in a code block/chunk, it acts as a comment indicator.

# Press Command + Return (Mac) or Control + Enter (PC) to run this code cell.
print(5/8)

0.625

In [2]:
# We can also use basic arithmetic operations
# Addition and division
4 + 5
print(10 / 2)



5.0


In [ ]:
# Exercise: Subtract 3 from 5, and multiply 3 by 5

# Subtraction
print(5-3)

# Multiplication
print(3*5)


2
15


# Variable Assignment
In Python, a variable allows you to refer to a value with a name.

To create a variable x with a value of 5, you use =, like this example:
`x=5`

You can now use the name of this variable, x, instead of the actual value, 5.

Note: = in Python means assignment, it doesn't test equality!



In [ ]:
#Example
# Create a variable savings with the value of 100.
savings=100
# Check out this variable.
print(savings)

100


In [3]:
# Exercise
# Suppose you start with $100 in savings.
#How much money would you have saved four months from now,
# if you saved $10 each month?

monthly_savings=10
months = 4
initial_savings = 100


total_savings = initial_savings + monthly_savings*months
print(total_savings)

print(100+10*4)


# Exercise
# Suppose you start with $100 in savings.
#How much money would you have saved four months from now,
# if you saved $100 each month?

monthly_savings=100
months = 4
initial_savings = 100

total_savings = initial_savings + monthly_savings*months
print(total_savings)

print(100+100*4)

# Now start with $200. What changes between these approaches?





140
140
500
500


In [ ]:
# Exercise

# Exercise
# Suppose you start with $100 in savings.
#How much money would you have saved four months from now,
# if you saved $100 each month?

monthly_savings=100
months = 4
initial_savings = 100

total_savings = initial_savings + monthly_savings*months
print(total_savings)

print(100+100*4)

# Now start with $200. What changes between these approaches?




# Other variable types
In the previous exercise, you worked with the integer Python data type `int`, or integer: a number without a fractional part. savings, with the value 100, is an example of an integer.

Next to numerical data types, there are three other very common data types/classes:

* `float`, or floating point: a number that has both an integer and fractional part, separated by a point. 1.1, is an example of a float.
* `str`, or string: a type to represent text. You can use single or double quotes to build a string.
* `bool`, or boolean: a type to represent logical values. It can only be True or False (the capitalization is important!).




In [ ]:
#Example
# Create a variable half
half=float(0.5)
half_again = 0.5

print(half)
print(half_again)

# Create a variable intro
intro="Hello! How are you?"

# Create a variable is_good
is_good=True

# Class Behavior
print("The class of 100 is", type(100))
print("The class of 'half' is",type(half))
print("The class of '100 + half' is",type(100+half))

double_intro = intro + intro
print(double_intro)


0.5
0.5
The class of 100 is <class 'int'>
The class of 'half' is <class 'float'>
The class of '100 + half' is <class 'float'>
Hello! How are you?Hello! How are you?


# Lists
A **list** is a compound data type; you can group values together, like this:

`a = "is"`

`b = "nice"`

`my_list = ["my", "list", a, b]`

In [ ]:
#Example - House Areas

hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [ ]:
# Example - House Areas

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


In [ ]:
# Example - List Subsetting

# Print out second element from areas
# Note: Python starts counting at 0
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Find the value in the last row and column of `house` (list of lists)
# Format is `list[row index][column index]`
print(house[-1][-1])
print(house[4][1])
print(house[-1][1])


11.25
9.5
9.5
9.5
9.5


## Example - List Subsetting
It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax: `my_list[start:end]`

The `start` index will be included, while the `end` index is not.

If you don't specify the start index, Python figures out that you want to start your slice at the beginning of your list. (Similar for end index.)


In [ ]:
# Example - List Subsetting

# Use slicing to create `downstairs`
downstairs = areas[0:6]
print(downstairs)

# Use slicing to create `upstairs`
upstairs = areas[6:]
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [ ]:
# Example - List Editing

# Correct the bathroom area
areas[-1] = 10.50

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

# Be careful!  What does `[1,2,3] + [4,5,6]` create?

print([1,2,3] + [4,5,6])

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
[1, 2, 3, 4, 5, 6]


In [ ]:
# Example - List Editing

areas_temp = areas_2
# Delete the poolhouse items from the list
del areas_temp[10]
del areas_temp[10]

# Print the updated list
print(areas_temp)
print(areas_2)
# Note that `areas_temp` and `areas_2` are the same now, but it seems that we only changed `areas_temp`
# This is because the variables `areas_temp` and `areas_2` are pointing to the same list



['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [ ]:
# Example - List Editing

# Let's fix the issue by explicitly calling `list()`
areas_2 = areas_1 + ["garage", 15.45]
areas_temp = list(areas_2)
del areas_temp[10]
del areas_temp[10]
print("The new areas_temp is \n", areas_temp)
print("The new areas_2 is \n", areas_2)

The new areas_temp is 
 ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]
The new areas_2 is 
 ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


# Functions

- Functions are reusable code blocks for specific tasks.
- Built-in functions like `type`, `max`, and `round` make coding more efficient.
- Functions can have optional arguments

# Example - Built-in Functions

- `print()`
- `type()`
- `str()`, `int()`, `bool()`, and `float()`
- `len()` for object length


# Example - I need help.

Use help(foo) or ?foo to see information about a function


In [4]:
# Example - Help Function
?pow

print(pow(2,3,2))
print(2**3)

# Note the required and optional arguments

0
8


In [5]:
# Class Example - Help Function


# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Combine the two lists, and use the function `sorted()`
# to arrange the values in decreasing order

?sorted

all = first + second #put them together in one list
sorted(all, reverse=True)




[20.0, 18.0, 11.25, 10.75, 9.5]

# Functions and Methods

- Everything in Python is an object, including strings, floats, and lists
- **Methods** are functions that belong to Python objects
    - Methods with the same name can behave differently based on the object type.
    - Some methods can modify the objects they're called on.

## Examples of methods

- *str* - `capitalize()`, `replace()`
- *float* - `bit_length()`, `conjugate()`
- *list* - `index()`, `count()`

In [ ]:
# Example

# Suppose you want to find the index of 'mom' in the list 'fam'
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

# Let's try something intuitive
index(fam, "mom")


NameError: name 'index' is not defined

In [ ]:
# Example - Dot Notation

#In order to call the method `index()`, we use "dot notation":
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
print(fam.index("mom")) # Call method index() on fam

# The method 'index()' belongs to the object 'fam'
# This is automatically included when the object is created

# Number of times the value '1.73' appears in the list 'fam':
print(fam.count(1.73))

print(fam.index("m"))


4
1


ValueError: 'm' is not in list

In [6]:
# Example - Dot Notation
sister = "Kari"
print(sister.index("r"))
print(sister.count("r"))
# Depending on the object, the method may behave differently




2
1


In [ ]:
# Example - List Methods
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50, 20.0]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50, 20.0]

# Use append twice to add poolhouse and garage size (24.5 and 15.45, respectively)
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

TypeError: slice indices must be integers or have an __index__ method

# Packages

What about other methods? Something a little more niche/nuanced/specialized?

Not everybody needs all of the functions or methods that are available, so these are not included in Python distributions

This is where *packages* come in!
- Packages are effectively directories of Python scripts (called modules)
- Examples include `NumPy` (for arrays), `Matplotlib` for data visualization, and `scikit-learn` for machine learning

**Note:** depending on how you access Python (cloud versions, local versions), you may need to manually download packages before installing.

## Installing Packages

**Note:** depending on how you access Python (cloud versions, local versions), you may need to manually download packages before installing. See this link for instructions if needed.

(https://packaging.python.org/en/latest/tutorials/installing-packages/)[https://packaging.python.org/en/latest/tutorials/installing-packages/]

In something like Jupyter Notebooks (via Google Colaboratory, etc.), many common packages are already available.



## Importing Packages
Before we can start using modules and methods from packages, we need to import the package (or specific module from the package).

We can do this with an `import` statement, like:

`import numpy`


In [ ]:
# Example - Importing Packages
# Use the 'array' function from `numpy`

import numpy
array([1,2,3])

# Note the error behavior here.
# `array()` is a function in the numpy package
# We need to be more specific about referencing that function

NameError: name 'array' is not defined

In [ ]:
# Example - Importing Packages
# Use the 'array' function from `numpy`

numpy.array([1,2,3])
# Try print() with this. Are the outputs different?
print(numpy.array([1,2,3]))

[1 2 3]


In [ ]:
# Example - Less Typing
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [ ]:
# Example - Be more selecive

# If we want to use only one function from a package, we can just import that function
# If you do this, you do not need to numpy. (or np.) notation to reference the function
from numpy import array
array([1,2,3])



### Which option is the best?

- `import numpy` followed by `numpy.array()` is the clearest version in code, but requires more typing
- `import numpy as np` followed by `np.array()` requires some human memory
- `from numpy import array` followed by `array()` requires the least coding, but hides some detail (requires more human memory)

The structure of `import numpy as np` is used very frequently. There are common shorthand names for many of the packages we'll see.


In [7]:
# Example - Pi
# Let's calculate the circumference and area of a circle with radius r=0.43.
# Circumference = 2*pi*r
# Area = pi*r^2

# The object `pi` doesn't exist in the main distribution of Python, but does exist in the `math` package
# Import the math package
import math

# Calculate C
C = 2 * 0.43 * math.pi

# Calculate A
A = pi * 0.43 ** 2  # `**` is used for exponentiation

print("Circumference: " + str(C))
print("Area: " + str(A))

# Why doesn't this work as it is currently?


NameError: name 'pi' is not defined

In [ ]:
# Example - Pi
#Common values (like pi) are reasonable objects to import directly

from math import pi
# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2  # `**` is used for exponentiation

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


### Importing from subpackages

Some packages are actually comprised of several packages (subpackages).

What does the following code do?

`from scipy.linalg import inv as my_inv`

`from scipy.linalg.matfuncs import inv as my_inv`




In [16]:
import scipy
dir(scipy.linalg.matfuncs)

['coshm',
 'cosm',
 'expm',
 'expm_cond',
 'expm_frechet',
 'fractional_matrix_power',
 'funm',
 'inv',
 'khatri_rao',
 'logm',
 'norm',
 'rsf2csf',
 'schur',
 'signm',
 'sinhm',
 'sinm',
 'solve',
 'sqrtm',
 'svd',
 'tanhm',
 'tanm']