<a href="https://colab.research.google.com/github/jppeirce/DSC210-Foundations-of-Data-Science/blob/main/Notes/04-intro_to_numpy/04-intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

**DSC 210 Foundations of Data Science**

References:
- [Hands-on Introduction to Data Science with Python](https://florian-huber.github.io/data_science_course/) (CC BY-NC-SA 4.0), and

## Learning objectives

1. Explain why plain lists fail for element-wise math.
2. Create NumPy arrays and use element-wise operations and broadcasting.
3. Filter data with boolean masks.
4. Work with 2D arrays: shape, indexing, slicing, transpose.
5. Compute summary statistics and a correlation.

# Introduction to NumPy (Numeric Python)

- NumPy and arrays
- Array methods

---
# 1. Why Arrays?
---
## 1.1 The issue with lists

Typically in Data Science, you'll often want to carry out operations over entire collections of values, and you want to do this fast.

With lists, this is a problem!

In [1]:
## Example - BMI
# RUN-TOGETHER

# Suppose we have height and weight data for a collection of people
# Our goal is to calculate BMI for each person
# We can calculate BMI as weight/height^2

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

bmi = weight/height**2

# This doesn't work. What's the issue?

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

 For a **list**, `**` and `/` are not defined element-by-element; there is no way to say "divide each weight by each height squared" without a loop. We want something that just does the math. That is NumPy.

## 1.2 NumPy to the Rescue!

 ** Note, you may need to install numpy on your own system prior to using the package **

NumPy provides an alternative to lists: arrays
- Similar to lists, but allow for calculations across the array
- Fast!

**Definition.** A NumPy *array* (`ndarray`) is an ordered collection of values, like a list, but with two superpowers: (1) math happens **element-wise** across the whole array, and (2) it is fast (the looping runs in compiled C, not Python).

One rule: NumPy arrays can contain only **one** type of data.

- If you create a "mixed" array, Python will convert the data to a more general type (like `str`)
- NumPy arrays are another type of object (like `str`, `float`, and `list`)

In [2]:
## Example - BMI
# RUN-TOGETHER
import numpy as np

height_m = np.array([1.73, 1.72, 1.61, 1.89, 1.79])
weight_kg = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = weight_kg/height_m**2
print(bmi)

# Calculations were performed element-wise
print(65.4/1.73**2)

[21.85171573 20.01081666 24.53609043 24.7473475  21.44127836]
21.85171572722109


Methods are associated with arrays, and may behave differently than other methods with the same name

### Activity: Predict, then run.
Lists and arrays react to `+` completely differently. Predict each result before running.

- `[1, 2, 3] + [1, 2, 3]`  is going to output _____
- `np.array([1,2,3]) + np.array([1,2,3])` is going to output _____

In [3]:
# RUN-TOGETHER
python_list = [1,2,3]   #S tandard list
numpy_array = np.array([1,2,3])   # Standard array

print(python_list + python_list)
print(numpy_array + numpy_array)

print(python_list[1])
print(numpy_array[1])

[1, 2, 3, 1, 2, 3]
[2 4 6]
2
2


### 1.3 The homogeneity rule

Because an array holds one type, mixing types forces a promotion to a common type. This is worth seeing on purpose so it never surprises you.

In [4]:
## Example
# FILL-IN-LIVE together: predict the type, then run. bool + int -> ?
mixed1 = np.array([True, 1, 2])
print(mixed1, '->', mixed1.dtype)

mixed2 = np.array([1, 2, 'go']) # int + str
print(mixed2, '->', mixed2.dtype)

[1 1 2] -> int64
['1' '2' 'go'] -> <U21


### 1.4 Broadcasting: array meets scalar

*Broadcasting* is how NumPy applies an operation between an array and a single value: the single value (called a scalar) is applied to every element.

In [5]:
# RUN-TOGETHER
import seaborn as sns
penguins = sns.load_dataset('penguins')
flippers_mm = penguins['flipper_length_mm'].dropna().to_numpy()

flippers_cm = flippers_mm / 10     # every value divided by 10
print('first five (mm):', flippers_mm[:5])
print('first five (cm):', flippers_cm[:5])

first five (mm): [181. 186. 195. 193. 190.]
first five (cm): [18.1 18.6 19.5 19.3 19. ]


### 1.5 Boolean masks: filtering without loops

Comparing an array to a value gives an array of `True`/`False`. Indexing an array *with* that boolean array keeps only the `True` positions. This replaces filtering loops and reads almost like English.

In [6]:
## Example - More subsetting approaches
# RUN-TOGETHER
#
# Recall:
print(bmi)

# Suppose we wanted to find all of the BMI values over 24
print(bmi > 24)  #creates a NumPy array of booleans

print('how many over 24:', sum(bmi>24)) # False = 0, True = 1

# Return only the values above 24, using the array of booleans
#print(bmi[bmi > 24])

[21.85171573 20.01081666 24.53609043 24.7473475  21.44127836]
[False False  True  True False]
how many over 24: 2


### Activity: Heavy Penguins

What fraction of penguins have weight more than 5 kg?

Fill in the following code chunk:

In [7]:
import seaborn as sns, numpy as np
penguins = sns.load_dataset('penguins')
mass_g = penguins['body_mass_g'].dropna().to_numpy()

# (1) Convert grams to kilograms (1000 g = 1 kg) by broadcasting.
mass_kg = mass_g / ____            # fill in
print('first five (kg):', mass_kg[:5])

# (2) How many penguins weigh more than 5 kg?
heavy = mass_kg[ ____ ]    # fill in the comparison
print('count over 5 kg:', len(heavy))

# (3) What fraction of all penguins is that?
print('fraction:', round(len(heavy) /  ______ , 3))

SyntaxError: '(' was never closed (957690800.py, line 11)

### Activity: Long Flippers

What fraction of penguins have flippers longer than 210 mm?

Fill in the following code chunk:

In [ ]:
# What is the total number of penguins with recorded flipper length
total = _____

# Now we mask out the flippers longer than 210 mm
long = flippers_mm[ _____ ]
# number of pengings with long flippers
n_long = _____
print('fraction of all penguins:', round(n_long/ total, 3))


### 1.6 NumPy Arrays

Let's look at the output `<class 'numpy.ndarry'>`
- The `numpy.` part indicates that the object was defined using the numpy package
- The `ndarray` part stands for 'n dimensional array'


In [ ]:
## Example - Baseball
# Import the numpy package as np

import numpy as np

# Heights of players in inches (source: stat.ucla.edu)
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

# What is the current data type of height_in?

# Create a numpy array from height_in:
height_in_array = np.array(height_in)

# Print out type of np_baseball
print(type(height_in_array))

**Definition.**
- `players.shape` is an *attribute* since it gives stored information and uses no parentheses.
- `players.mean()` is a *method* since it is an action and uses parentheses.

In [ ]:
print('a function approach: ', len(height_in_array))
print('using a attribute: ', height_in_array.size)

# vs. an action
print('using a method: ', height_in_array.mean())

# methods can be stacked!
print('using another method: ', height_in_array.mean().round(2))


---
# 2. 2D Arrays, Statistics, and Correlation
---

## 2.1 Two-dimensional arrays

Real data are often organized in a table: many rows, several columns. NumPy represents that as a **2D array**. Now `shape` matters and indexing takes a `[row, column]` pair.

In [8]:
# RUN-TOGETHER
import numpy as np

# rows = [heights (in)], [weights (lb)]
players = np.array([[74, 74, 72, 72, 73, 69, 69, 71],       # heights
                    [180, 215, 210, 210, 188, 176, 209, 200]])  # weights

# size does not work to find the dimensions of n-dimentional arrays
print('size of an array: ', players.size)

# instead we use the shape attribute
#print('shape (rows, cols):', players.shape)

size of an array:  16


In data science, we commonly want our data arranged in a different way than what we see in `players`. We prefer that each row is an observational unit (i.e. player) and each column is a feature (i.e height, weight).

We will need to swap rows and the columns so that the height, weight rows become height, weight columns. This can easily be done by using the transpose attibute.

In [9]:
print('original:\n', players) # \n forces a line break
players_dat = players.T
print('transposed:\n', players_dat)

original:
 [[ 74  74  72  72  73  69  69  71]
 [180 215 210 210 188 176 209 200]]
transposed:
 [[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 188]
 [ 69 176]
 [ 69 209]
 [ 71 200]]


### 2.1 Indexing and slicing of 2D arrays

> array_name[row, column] produces the element in location (row, column)

Note, in Python:
- indexing starts a 0
    - `array_name[0,0]` is the element in first row and first column.
    - `array_name[-1,-1]` is the last element (negative counts from the end).
- `:` produces all values
- `array_name[row]` or `array_name[row, :]`produces the single row indexed by `row`
- `array_name[:, column]` produces the single column indexed by `column`

We can slice vales from rows, from columns, or both using the notation `start:stop`
- Remember: the slice is from `start`, up to but **not including** `stop`.


In [10]:
print(players_dat)

# data for first player
print('player 0:', players_dat[0])

# Access the element in the third row and first column
print(players_dat[2,0]) # Remember 0 indexing!
print(players_dat[2][0]) # also works!

# Access the elements for the forth and fifth person
# Think first:
# start = 3: fouth person is in row 3 because index starts at 0
# end = 5: need one more than where we want to stop
print('fourth and fifth:\n', players_dat[3:5,:])

# boolean mask heights < 70
# Think first:
# first column of heights: players_dat[:,0]
# boolean mask: players_dat[:,0] < 70  -> False False ....
print('height < 70:\n', players_dat[players_dat[:,0] < 70, :] )

[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 188]
 [ 69 176]
 [ 69 209]
 [ 71 200]]
player 0: [ 74 180]
72
72
fourth and fifth:
 [[ 72 210]
 [ 73 188]]
height < 70:
 [[ 69 176]
 [ 69 209]]


### Activitiy

Complete the following code block to ...

In [ ]:
# Example - Baseball

baseball = [height_in, weight_lb]
np_baseball = np.array(baseball)
print(np_baseball.shape) #Note the order of the dimensions
print(np_baseball[:, 0:1])

np_baseball_long = np_baseball.T # .T method transposes rows and columns
print(np_baseball_long.shape)
print(np_baseball_long[0:1, :])

# Convert to metric
conversion = np.array([0.0254, 0.453592])
np_baseball_m = np_baseball_long*conversion
print(np_baseball_m[0:1,:])

# Basic Statistics

What can we do with this data?

NumPy functions:
- mean()
- median()
- corrcoef()
- std()
- sum()
- sort()


In [ ]:
# Example - Baseball Statistics
print(np.mean(np_baseball_m[:,0])) # Average height (m)
print(np.mean(np_baseball_m[:,1])) # Average weight (kg)

print(np.corrcoef(np_baseball_m[:,0], np_baseball_m[:,1]))



In [ ]:
# Example - Baseball Statistics
import numpy as np
# Fancier output:
print("Average Height: " + str(round(np.mean(np_baseball_m[:,0]),2))) # Note the use of str()
print("Correlation: " + str(np.corrcoef(np_baseball_m[:,0], np_baseball_m[:,1])[0,1]))